#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: 'An introduction to data visualization using Tableau Public with real-world traffic data.'

# Overall title for pages.
title: 'Intro to Data Visualization with Tableau Public'

# Date the lesson was created (YYYY-MM-DD)
created: 2025-05-10

# Comma-separated list of keywords for the lesson
keywords: 'tableau, data visualization, dashboards, traffic data, maps, public data, The Carpentries'

# Life cycle stage of the lesson
life_cycle: 'pre-alpha'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/jt14den/carpentries-tableau-intro'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'tdennis@library.ucla.edu'

# Navigation ------------------------------------------------

# Order of episodes in your lesson
episodes: 
- introduction.md
- exploring-data.md
- creating-visualizations.md
- adding-interactivity.md
- building-dashboards.md


# Information for Learners
learners: 
- setup.md

# Information for Instructors
instructors: 
- instructor-notes.md

# Learner Profiles
profiles: 
- learner-profile.md

# Customisation ---------------------------------------------
# Add any custom settings below here
